### ISSUE TITLE
Process 별 function 구현

### ISSUE THREAD

**Issue by chandryou** [statgarten/goophi#1]
Tidymodels의 로직에 따라  set_engine, set_mode, fit 이 3가지를 따로따로의 process로 해서 
engine에서 machine learning model을 선택 (다수도 가능)하고 set_mode, fit 에서 각각의 process에 사용자가 원하는 configuration을 구현할 수 있도록 하면 좋겠습니다.

@ycseong07

**Comment by ycseong07** [comment]
_1. Tidymodels의 로직에 따라 set_engine, set_mode, fit 이 3가지를 따로따로의 process로 해서 engine에서 machine learning model을 선택_ 
- set_engine, set_mode는 알고리즘 선택 시 함께 입력받고, fit은 grid search with cross validation 단계에서 진행하도록 구성했습니다.

_2. (다수도 가능)하고_ 
- 최종 모델들을 리스트에 저장해두고, 여러 모델의 결과를 보여줄 수 있도록 구성했습니다.

_3. set_mode, fit 에서 각각의 process에 사용자가 원하는 configuration을 구현할 수 있도록 하면 좋겠습니다._
- set_mode는 1과 같이 구성했습니다.  
- fit은 k-fold cross validation에서 진행되고, k는 선택 가능하도록 구성했습니다. 유저가 선택한 model, engine에 따라 customizing할 수 있는 hyperparameter grid를 shiny app에서 동적으로 입력 받을 수 있게 구성할 예정입니다.

**Comment by ycseong07** [comment]
해당 피드백 반영 완료했습니다. 다만 하나의 함수로 여러 기능을 수행하려다 보니 set_engine, set_mode, fit 부분을 독립적인 기능으로 빼지는 못했습니다. 추후 버전업 시에 우선적으로 반영하겠습니다.
