### ISSUE TITLE
warning 조건 documentation

### ISSUE THREAD

**Issue by jhk0530** [statgarten/goophi#12]
모델 생성 등에서 데이터가 조건을 갖춰야하는 경우. 어떤 경우 인지 작성해주세요. 
이를 기반으로 추후 shiny 에서 warning 올리는 작업 예정입니다.

ex)
- data has `NA`, 
- data is not `factor`

**Comment by ycseong07** [comment]
## Uploaded data Tab
1. Data에 NA가 존재하는 경우 -> Data must not contain NA.
2. Column A, Column B에 String 형태가 값으로 들어가 있을 경우 -> The column with categorical variables  must be a factor: Column A, Column B
3. Column A (혹은 여러 column) 에 Date 형태가 값으로 들어가 있을 경우 -> Our ML service does not support modeling including data with date column(s).
4. Column A, Column B가 하나의 값으로 채워져 있을 경우 -> Columns having same values for all observations should be excluded from the modeling: Column A, Column B

## Modeling Tab - goophi에서 예외처리
1. Mode == Classification 일 경우, targerVar 파라미터는 factor, Mode == Regression 일 경우, targerVar 파라미터는 numeric이어야 함.
-> For Regression, the parameter 'targerVar' should be numeric. / For Classification, the parameter 'targerVar' should be factor.
