### ISSUE TITLE
hex sticker design issue

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/goophi#13]
패키지의 hex sticker 디자인을 해보려고 하는데요.
패키지에 대한 간단한 소개 + 이름을 지은 목적에 대해서 reply 해주시면 참고해 보도록 하겠습니다.

**Comment by ycseong07** [comment]
goophi 패키지의 명칭 변경에 대해, 파이 내부적으로는 stove로 바꾸면 어떨까하고 생각하고 있습니다. 데이터를 ML 알고리즘을 통해 분석하는 일련의 과정을 쿠키틀로 쿠키를 찍어내는 데에 많이 비유를 하더라구요. 저희 ML 패키지가 backbone으로 사용하는 tidymodels 역시 이에 착안했는지 recipe, bake, juice 등의 함수명을 사용하구요. 데이터를 잘 조리한다는 의미로 stove가 어떨까하는데, 혹시 다른 의견이 있으시다면 고려하겠습니다!
