### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by katyalex** [statgarten/goophi#17]
I used this package to create an ML model and got pretty good accuracy. However, I couldn't find a way to get the hyperparameters for the model. How can I get the hyperparameters of my best model?

**Comment by ycseong07** [comment]
Currently, the function for getting hyperparameters of best model is not implemented, but I think it is necessary. This package combines some of the packages of tidymodels ecosystem, so it is not difficult to extract the combination of hyperparameters of the best model using the select_best() function. I will add this function soon. Thanks :)

**Comment by ycseong07** [comment]
I added the variable 'bestParams' to the list returned by the fitBestModel() function in fitting.R. Thank you for your advice @katyalex
